### ISSUE TITLE
URI for inserting a new image in Word document refers to https instead of http

### ISSUE THREAD

**Issue by tdceus** [OfficeDev/open-xml-docs#51]
The example "how-to-insert-a-picture-into-a-word-processing-document" contains a namespace error for the URI.

             new A.PresetGeometry(
                                     new A.AdjustValueList()
                                 ) { Preset = A.ShapeTypeValues.Rectangle }))
                     ) { Uri = "https://schemas.openxmlformats.org/drawingml/2006/picture" })

must be

             new A.PresetGeometry(
                                     new A.AdjustValueList()
                                 ) { Preset = A.ShapeTypeValues.Rectangle }))
                     ) { Uri = "http://schemas.openxmlformats.org/drawingml/2006/picture" })

Then this example will work.

**Comment by p-kaczynski** [comment]
Sadly haven't noticed this issue, and it took me a while to track the issue I've been having. I have opened #52 with the fix yesterday due to that.

**Comment by jwisener** [comment]
The freaking sample code doesn't work boo!

**Comment by lindalu-MSFT** [comment]
Hi I merged this but there's a build error on the docfx.json that I'm trying to figure out. Thanks for catching this.

**Comment by shapeh** [comment]
@tdceus - thank you so much. I have just wasted three hours figuring out what was going on here. The change to `http` from `https `worked for me. 

@lindalu-MSFT - Another suggestion is to update the sample code in general. Please make it more versatile, and allow for adding several files.

Some issues are not really clear, such as the parameter `EditId`:

             {
                 DistanceFromTop = (UInt32Value)0U,
                 DistanceFromBottom = (UInt32Value)0U,
                 DistanceFromLeft = (UInt32Value)0U,
                 DistanceFromRight = (UInt32Value)0U,
                 EditId = "50D07946" // why is this a fixed string / what is the meaning of EditId?
             });

Also:

             new PIC.NonVisualDrawingProperties()
             {
                 Id = (UInt32Value)0U, // is this always fixed? What happens when we add more images - do we need to update the Id?
                 Name = "New Bitmap Image.jpg"
             },

Next, in the code you reference:

`string fileName = @"C:\Users\Public\Documents\MyPic.jpg"; // MyPic.jpg`

However, the name in code is still `New Bitmap Image.jpg` - does it really matter what name you are using?:

               new PIC.NonVisualDrawingProperties()
               {
                   // ...
                   Name = "New Bitmap Image.jpg"
               },

**Comment by sdudnic** [comment]
not fixed
https://docs.microsoft.com/en-us/office/open-xml/how-to-insert-a-picture-into-a-word-processing-document

**Comment by sdudnic** [comment]
Also please don't hardcode

```
            // Define the rendered image size
            Size size = new Size(400, 300);

            Int64Value width = size.Width * 9525;
            Int64Value height = size.Height * 9525;
            
            // Define the reference of the image.
            var element =
                 new Drawing(
                     new DW.Inline(
                         new DW.Extent() { Cx = width, Cy = height },

```

**Comment by p-kaczynski** [comment]
Now, to be fair, the OOXML is a nightmare and the docs are not enough to deal with it. I have been working with it for a while now and the process looks like follows:

1. Open MS Word
2. Write whatever you want to develop
3. Open in Open XML Productivity Tool
4. Check how word generated that
5. Reflect code
6. Refactor code so it's not a nightmare
7. Replicate MS Word behaviour

Other docs for the OOXML are actually more useful often - just google (or bing) for the "OOXML <xml tag name of OOXML>" and you will get a decent explanation of what's what.

Also a protip: most wordprocessors that open docx files don't care about it, but MS Word OFTEN CARES about the order of things, so a `RunProperties` must have `RunFonts` before `Color` or else...

**Comment by shapeh** [comment]
@p-kaczynski OOXML is indeed a nightmare. It seems like MS is not really putting too much effort in the documentation. Last comment on this thread is 6~ months old.

@lindalu-MSFT, can you please update us on any status?

**Comment by lindalu-MSFT** [comment]
You're correct, we don't have any resources dedicated to monitoring this repo. If you create a PR with your suggested updates, I'll review and merge them in. Today I fixed the build error and did merge some changes including [this one](https://github.com/OfficeDev/open-xml-docs/pull/52) to production.

**Comment by sdudnic** [comment]
@lindalu-MSFT fixed in C#, but not fixed in VB.NET on the article I linked above

**Comment by T4ssilo** [comment]
Article [https://docs.microsoft.com/en-us/office/open-xml/structure-of-a-spreadsheetml-document](https://docs.microsoft.com/en-us/office/open-xml/structure-of-a-spreadsheetml-document) contains https schema locations in namespaces, which don't work for me when building a spreadsheet from scratch.

**Comment by lindalu-MSFT** [comment]
@T4ssilo you could try reaching out to developers on Stack Overflow and see if anyone can help. Or go to Microsoft Q+A and ask a question there. You have a way better chance of having your questions answered in one of these community forums instead of this repo that currently isn't being monitored. (Except by me, but not in any official capacity! I just like to be sure that customers at least get a response from someone, even if it's "sorry I can't help!")

**Comment by mikeebowen** [comment]
closed by 
- #296
